spring:
  application:
    name: position-tracking
  data:
    mongodb:
      uri: mongodb://mongodb:27017/position
      auto-index-creation: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8082
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.cloud: DEBUG