server:
  port: 8080
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: redis
      port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000