services:
  donation-history-service:
    build: .
    ports:
        -"8081:8081" 
    depends on:
      -mongo-db
    envirement:
      -SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/blooddonation_db
    mongodb:
     image: mongo:latest
     ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:    


 